Repository Team-Detective/tomatoes, pull requests merged in 2024-10, with the labels that each got.

#6 Feat: 공용 버튼 컴포넌트 리팩토링 및 범용성 향상 작업 #5
  src/app/page.tsx
  src/components/common/BannerLink.tsx
  src/components/common/Button.tsx
Labels: 🎨디자인

#11 Feat: 헤더 및 네비게이션 바 구현 작업 #10
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/ui/Header.tsx
  src/components/ui/NavItem.tsx
  src/components/ui/Navigation.tsx
  tailwind.config.ts
Labels: 🚀기능 구현, 🎨디자인

#12 공용컴포넌트 Footer 작업 #7
  src/components/common/Footer.tsx
Labels: 🚀기능 구현, 🎨디자인

#13 Feat: 공통 컴포넌트 중 태그, 디데이 구현
  package-lock.json
  package.json
  src/app/page.tsx
  src/components/common/Dday.tsx
  src/components/common/Tag.tsx
Labels: 🚀기능 구현, 🎨디자인

#14 Feat: 공용 컴포넌트 Search Bar 구현 작업
  package-lock.json
  package.json
  src/app/page.tsx
  src/components/common/SearchBar.tsx
Labels: 🚀기능 구현, 🎨디자인

#15 Docs: 리드미 초안 작성
  README.md
Labels: 🎸기타

#17 Design: tailwind 커스텀 색상 변경 및 기타 수정 작업 #16
  README.md
  src/app/globals.css
  src/components/common/BannerLink.tsx
  src/components/common/Dday.tsx
  src/components/common/Footer.tsx
  src/components/common/SearchBar.tsx
  src/components/common/Tag.tsx
  src/components/ui/Navigation.tsx
  tailwind.config.ts
Labels: 🎨디자인, 🎸기타
